### ISSUE TITLE
How to handle student grades

### ISSUE THREAD

**Issue by rogermule** [EduSec/EduSec#16]
How can I handle student grades? Does the system allow students' grades to be added? Does it allow course add and drop as well as course level re-exam for students? Furthermore, does it allow Certificates and Documents Management for printing official and temporary degrees for students?

**Comment by EduSec** [comment]
Hi Rogermule,

Kindly note open-source EduSec has limited functionalities and since 2017 there are no updates provided by the community. 
Now EduSec enterprise version in a cloud-based system. Please check attached document for detailed feature list.
Feel free to contact me at info@rudrasoftech.com 
Thank you.
[EduSec Enterprise Version Features.pdf](https://github.com/EduSec/EduSec/files/5253336/EduSec.Enterprise.Version.Features.pdf)
